Repository algolia/algoliasearch-client-ruby, pull requests merged in 2019-09, with the labels that each got.

#362 fix(mcm-tests): update tests to make them pass
  .travis.yml
  spec/client_mcm_spec.rb
Labels: Bug

#358 Add exists method
  lib/algolia/index.rb
  spec/client_spec.rb
Labels: API feature, Ready

#361 feat: remaining validity
  lib/algolia/client.rb
  lib/algolia/error.rb
  spec/client_spec.rb
Labels: API feature, Ready

#359 added(index): unit testing relevance helpers
  lib/algolia/error.rb
  lib/algolia/index.rb
  spec/client_spec.rb
Labels: API feature, Ready

#364 fix(exists-method): fix method syntax with an alias
  lib/algolia/index.rb
  spec/client_spec.rb
Labels: Enhancement
